version: "3.9"

services:

  db:
    image: postgres
    restart: "no"
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    

  python-flask:
    build: .
    restart: "no"
    ports:
      - "5000:5000"
    volumes:
      - ./src:/usr/src/app/src
    